### ISSUE TITLE
Link for bee-image-finder package doesn't seem to exist

### ISSUE THREAD

**Issue by EitanRashkovan** [Big-Bee-Network/visual-acuity-data#1]
Hello Katja,
Unfortunately it seems that the link for the bee-image-finder package doesn't lead anywhere (it takes me to a 404 error github page)
[https://github.com/Big-Bee-Network/bee-image-finder)[https://github.com/Big-Bee-Network/bee-image-finder]](https://github.com/Big-Bee-Network/bee-image-finder)%5Bhttps://github.com/Big-Bee-Network/bee-image-finder%5D)
I am not sure if I messed something up or the page actually doesn't exists but downloading the high quality images into separate folders is a vital step for our project and having this package work would help speed up the process.
Please advice with any help/solutions to this problem, Eitan

**Comment by seltmann** [comment]
https://github.com/Big-Bee-Network/bee-image-finder 

The link was just not rendering correctly, but I suspect you figured that out! I am out of town through next week (May 15) but can help after I return if you need it.

**Comment by seltmann** [comment]
fixed link
